### PR TITLE
deb: install missing manpages

### PR DESCRIPTION
**Pull request by kenhys**
These files are generated by the following comamnds:

  help2man -m "TD-AGENT" /usr/bin/td -o td.1
  help2man -m "TD-AGENT" /usr/bin/td -o td-agent.1
  help2man -m "TD-AGENT" /usr/bin/td -o td-agent-gem.1

Then modified a bit that it isn't correct entry
such as missing .info references.

### CODE REVIEW

**Comment by kenhys** [comment]
Ops!, CI fails on debian-buster.

**Comment by kenhys** [comment]
`rake apt:build APT_TARGETS="debian-buster"` passed on local PC...

**Comment by kenhys** [comment]
I could reproduce it. so I'll investigate it.

**Comment by kenhys** [comment]
I've fixed to pass CI.

**Comment by ashie** [comment]
> These files are generated by the following comamnds:
> 
> help2man -m "TD-AGENT" /usr/bin/td -o td.1
> help2man -m "TD-AGENT" /usr/bin/td -o td-agent.1
> help2man -m "TD-AGENT" /usr/bin/td -o td-agent-gem.1
> 
> Then modified a bit that it isn't correct entry
> such as missing .info references.

I'm feeling uncomfortable with this comment, since these files contains following lines:

```
.\" DO NOT MODIFY THIS FILE!  It was generated by help2man 1.47.15.
```

It seems that most of your modifications can be done by help2man's options.

```
$ LANG=C help2man 
`help2man' generates a man page out of `--help' and `--version' output.

Usage: help2man [OPTION]... EXECUTABLE

 -n, --name=STRING       description for the NAME paragraph
 -s, --section=SECTION   section number for manual page (1, 6, 8)
 -m, --manual=TEXT       name of manual (User Commands, ...)
 -S, --source=TEXT       source of program (FSF, Debian, ...)
 -L, --locale=STRING     select locale (default "C")
 -i, --include=FILE      include material from `FILE'
 -I, --opt-include=FILE  include material from `FILE' if it exists
 -o, --output=FILE       send output to `FILE'
 -p, --info-page=TEXT    name of Texinfo manual
 -N, --no-info           suppress pointer to Texinfo manual
```

e.g.)

```
$ help2man -n "Treasure Data Toolbelt" -m "TD-AGENT" --no-info /usr/bin/td -o td.1
```

**Comment by ashie** [comment]
There is only one thing that can't be editted by help2man:

```diff
-http://guides.rubygems.org
+https://guides.rubygems.org
```

It should be fixed at upstream.

**Comment by kenhys** [comment]
> $ help2man -n "Treasure Data Toolbelt" -m "TD-AGENT" --no-info /usr/bin/td -o td.1

Thanks!

**Comment by kenhys** [comment]
I'll fix PR again.

**Comment by kenhys** [comment]
@ashie 

> It should be fixed at upstream.

I've found that already fixed in upstream.

https://github.com/ruby/ruby/blob/master/lib/rubygems/command.rb#L651

**Comment by ashie** [comment]
> I've found that already fixed in upstream.
> 
> https://github.com/ruby/ruby/blob/master/lib/rubygems/command.rb#L651

I see. Thanks!

**Comment by kenhys** [comment]
@ashie 

I've regenerated and fixed commit message.

**Comment by ashie** [comment]
Thanks!

**Pull request merged**
