### PR TITLE
deb: add missing copyright

### PR DESCRIPTION
**Pull request by kenhys**
It follows https://www.debian.org/doc/packaging-manuals/copyright-format/1.0/

### CODE REVIEW

**Comment by kenhys** [comment]
I've changed to generate copyright.
but need to fix empty licenses

**Comment by kenhys** [comment]
I'll change to collect gem specification from bundled gem files now.

**Comment by kenhys** [comment]
Fixed. I 'm checking build now

**Comment by kenhys** [comment]
still no copyright, I'm debugging now.

**Comment by kenhys** [comment]
now changing to contain d/copyright to archive.

**Comment by ashie** [comment]
Thanks!

**Pull request merged**
