### PR TITLE
Add arm64 support to ubuntu focal

### PR DESCRIPTION
**Pull request by repeatedly**
I tested this patch with https://github.com/clear-code/td-agent-builder/pull/24 and build stops by lintian phase.
Does anyone check this patch?

### CODE REVIEW

**Comment by ashie** [comment]
```
$ pstree
...
        |-containerd-+-containerd-shim-+-build.sh-+-debuild-+-lintian-+-nproc
        |            |                 |          |         |         `-{lintian}
        |            |                 |          |         |-tee---{tee}
        |            |                 |          |         `-{debuild}
        |            |                 |          `-{build.sh}
        |            |                 `-9*[{containerd-shim}]
        |            `-34*[{containerd}]
...
```

```
$ ps axl | grep nproc
4     0  286573  286558  20   0      0     0 -      Z+   pts/0      0:00 [nproc] <defunct>
```

**Comment by kenhys** [comment]
A brief survey:

https://packages.ubuntu.com/search?suite=focal&arch=arm64&searchon=names&keywords=lintian
lintian 2.62 is used.
https://bugs.launchpad.net/ubuntu/+source/lintian 
It seems that it is not already known issue.
https://bugs.debian.org/cgi-bin/pkgreport.cgi?archive=both;repeatmerged=on;src=lintian 
It seems that it is not already known issue even though archive.(I've expected something to do with 2.62-2.76)

**Comment by ashie** [comment]
This pull request itself is no problem, I merge it.
We should support also ubuntu-focal-arm64.
We'll track the lintian's issue at #65.

**Comment by ashie** [comment]
Until the issue is resolved, we'll avoid this issue by #66
```
LINTIAN=no rake apt:build APT_TARGETS=ubuntu-focal-arm64
```

**Pull request merged**
