### PR TITLE
WIP: rpm: apply rpmlint -i for making package in good shape

### PR DESCRIPTION
**Pull request by kenhys**

### CODE REVIEW

**Comment by ashie** [comment]
Since it reports too many issues with the current code, I'll merge this pull request after major issues are resolved.

**Comment by kenhys** [comment]
I got it.

**Comment by kenhys** [comment]
I've rebased with recent master.

**Comment by ashie** [comment]
> I'll merge this pull request after major issues are resolved.

I think major issues are resolved or suppressed.
We'll continue to resolve several remaining issues.

**Pull request merged**
